- hosts: server
  vars:
    image: riswonowo/docker-ansible:beta
  tasks:
    - name: install python-docker ubuntu
      apt:
        name: python-docker
        state: present
      when:
      - ansible_distribution == "Ubuntu"
    - name: install python-docker centos
      apt:
        name: python-docker
        state: present
      when:
      - ansible_distribution == "CentOS"  
    - name: pull image
      docker_image:
         name: "{{ image }}"
         state: present
         force: yes
    - name: create container
      docker_container:
         recreate: yes
         name: docker_ansible
         state: started
         force: yes    
         image: "{{ image }}"
         exposed_ports:
         - 8089:80
         published_ports:
         - 8089:80
        
